// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg_ID.proto
#pragma warning disable 1591, 0612, 3021





public enum MessageID
{

    #region Msg_Account.proto

    /// <summary>
    ///登录
    /// </summary>
    MsgLoginReq = 1000001,
    MsgLoginAck = 2000002,

    /// <summary>
    ///注册
    /// </summary>
    Msg_RegisterRq = 1900009,
    Msg_RegisterRs = 2000004,

    /// <summary>
    ///获取验证码
    /// </summary>
    Msg_RegisterCodeRq = 1900008,
    Msg_RegisterCodeRs = 2000005,

    /// <summary>
    ///改名
    /// </summary>
    ModifyUserReq = 4000102,
    ModifyUserAck = 2000102,


    /// <summary>
    ///心跳包
    /// </summary>
    MsgPingReq = 1900003,
    MsgPingAck = 2000003,

    /// <summary>
    ///设置安全密码
    /// </summary>
    Msg_SetSafeCodeRq = 4000103,
    Msg_SetSafeCodeRs = 2000103,

    /// <summary>
    ///上锁
    /// </summary>
    Msg_LockRq = 4000104,
    Msg_LockRs = 2000104,


    /// <summary>
    ///解锁
    /// </summary>
    Msg_UnlockRq = 4000105,
    Msg_UnlockRs = 2000105,

    /// <summary>
    ///系统消息
    /// </summary>
    Msg_SysMsgRq = 4000106,

    //官方通告2000106
    Msg_SysMsgRs = 2000106,


    //官方通告推送2100008
    Msg_SynSystemMsg = 2100008,

    //奖池资金变动推送2100009
    Syn_Jackpot = 2100009,


    /// <summary>
    ///发送消息4000111
    /// </summary>
    Msg_ChatMsgRq = 4000111,
    Msg_ChatMsgRs = 2000111,

    /// <summary>
    ///推送聊天消息21000017
    /// </summary>
    Msg_SynChatMsg = 2100017,

    //获取我的聊天消息列表4000112
    Msg_ChatMsgListRq = 4000112,
    Msg_ChatMsgListRs = 2000112,

    //购买VIP4000113
    Msg_BuyVipRq = 4000113,

    //2000236
    Msg_BuyVipRs = 2000236,

    //钻石变化2000237
    Msg_SynDiamondChange = 2000237,

    //资金消息4000114
    Msg_GoldMsgRq = 4000114,
    //资金消息返回 2000113
    Msg_GoldMsgRs = 2000113,

    //欢乐豆变化 2000264
    Msg_SynCoinChange = 2000264,

    /// <summary>
    /// 2000270
    /// 消耗配置 兑换配置
    /// key  1：带入消耗欢乐豆数  2：一钻石兑换欢乐豆比例 3:一钻石兑换联盟币数量
    /// </summary>
    Msg_SystemConfigRq = 4000231,
    Msg_SystemConfigRs = 2000270,

    Msg_DiamondChangeCoinRq = 4000232,
    Msg_DiamondChangeCoinRs = 2000271,

    //金币礼包4000234
    Msg_CoinGiftRq = 4000234,
    Msg_CoinGiftRs = 2000115,

    //联盟币礼包4000235
    Msg_GoldGiftRq = 4000235,
    Msg_GoldGiftRs = 2000116,

    //修改密码4000117
    Msg_ModifyPwdRq = 4000117,
    Msg_ModifyPwdRs = 2000273,

    //申请处理结果4000118
    Msg_getApplyOptionMsgRq = 4000118,
    Msg_getApplyOptionMsgRs = 2000117,
    Msg_SynApplyMsg = 2000118,

    //推送新消息通知2100020
    Msg_SynRedDot = 2100020,

    //推送聊天未读消息数量2100021
    Msg_SynChatMsgState = 2100021,

    //推送聊天未读消息数量2100022
    Msg_SynChatMsgStateList = 2100022,

    //联盟币变动2000277
    Msg_SynClubCurrencyChange = 2000277,

    //跑马灯推送2100026
    Msg_SynPmdMsg = 2100026,



    #endregion

    #region Msg_Common.proto


    /// <summary>
    ///错误码
    /// </summary>
    Msg_Error = 2000001,

    #endregion

    #region  Msg_Desk.proto

    /// <summary>
    ///前端创建请求
    /// </summary>
    Msg_CreateDeskRq = 1900005,

    /// <summary>
    ///牌桌列表
    /// </summary>
    Msg_DeskListRq = 4000301,
    Msg_DeskListRs = 2000214,

    /// <summary>
    ///解散牌桌
    /// </summary>
    Msg_DisMissDeskRq = 5001002,
    Msg_DisMissDeskRs = 2100002,


    /// <summary>
    ///进入桌子
    /// </summary>
    Msg_EnterDeskRq = 4000302,

    /// <summary>
    ///切换牌桌
    /// </summary>
    Msg_ChangeDeskRq = 5001029,

    /// <summary>
    ///离开桌子
    /// </summary>
    Msg_LeaveDeskRq = 5001004,
    Msg_LeaveDeskRs = 2000211,

    /// <summary>
    ///坐下
    /// </summary>
    Msg_SitDownRq = 5001005,


    /// <summary>
    ///站起
    /// </summary>
    Msg_SitUpRq = 5001008,
    Msg_SynSitUp = 2000217,

    Msg_SitUpRs = 2000218,//不是等待，或者结算时候发
    /// <summary>
    ///请求带入
    /// </summary>
    Msg_BringRq = 4000303,
    Msg_BringRs = 2000215,

    Msg_SynDeskStart = 2000275,



    /// <summary>
    ///处理请求带入申请
    /// </summary>
    Msg_BringOptionRq = 4000304,
    Msg_BringOptionRs = 2000216,

    /// <summary>
    /// 查看玩家信息(德州)
    /// </summary>
    Msg_PlayerInfoRq = 4000305,
    Msg_PlayerInfoRs = 2000518,

    //房主拒绝了带入请求2000219
    Msg_SynRefuseBring = 2000219,

    /// <summary>
    ///带入申请
    /// </summary>
    Msg_SynBringInfo = 2100003,
    Msg_BringList = 2100004,
    Msg_getBringListRq = 4000236,

    /// <summary>
    ///推送桌子玩家信息
    /// </summary>
    Syn_DeskPlayerInfo = 2000212,
    Syn_DeskPlayerInfo1 = 2000274,
    Syn_DeskPlayerInfo2 = 2000278,

    /// <summary>
    ///房主开始游戏
    /// </summary>
    Msg_Start = 5001006,


    /// <summary>
    ///桌子创建成功返回
    /// </summary>
    DeskCommonInfo = 2000209,

    /// <summary>
    ///牌局结束记录
    /// </summary>
    SingleGameRecord = 2000220,

    /// <summary>
    ///我的战绩
    /// </summary>
    My_GameRecordRq = 4000107,

    /// <summary>
    ///战绩信息
    /// </summary>
    My_GameRecordRs = 2100011,

    /// <summary>
    ///战绩详情 4000108
    /// </summary>
    Msg_GameRecordDetailRq = 4000108,
    Msg_GameRecordDetailRs = 2100014,


    /// <summary>
    ///账本请求 5001010
    /// </summary>
    Msg_AccountBookRq = 5001010,
    Msg_AccountBookRs = 2000222,

    /// <summary>
    ///桌子内聊天 5001011 
    /// </summary>
    Msg_DeskChatRq = 5001011,
    Msg_SynDeskChat = 2000223,//广播聊天信息 2000223
    Msg_SynDeskChatHistory = 2000224,//推送历史桌子聊天信息

    /// <summary>
    ///禁言 5001012
    /// </summary>
    Msg_ForbidChatRq = 5001012,
    Msg_ForbidChatRs = 2000225,//
    Msg_SynForbid = 2000226,//通知玩家禁言2000226

    /// <summary>
    ///踢出玩家5001013
    /// </summary>
    Msg_ClickPlayerRq = 5001013,
    Msg_ClickPlayerRs = 2000227,//
    Msg_SynClick = 2000228,//通知玩家被踢出2000228

    /// <summary>
    ///礼物
    /// </summary>
    Msg_SendGiftRq = 5001014,
    Msg_SynSendGift = 2000229,//

    /// <summary>
    ///取消留座离桌5001015
    /// </summary>
    Msg_CancelLeaveRq = 5001015,
    Msg_CancelLeaveRs = 2000231,
    Msg_SynPlayerState = 2000230,

    /// <summary>
    ///房间暂停5001016
    /// </summary>
    Msg_PauseDeskRq = 5001016,
    Msg_PauseDeskRs = 2000232,
    Msg_SynDeskState = 2000233,

    /// <summary>
    ///房间续时5001017
    /// </summary>
    Msg_DeskContinuedTimeRq = 5001017,
    Msg_DeskContinuedTimeRs = 2000234,
    Msg_SynDeskContinuedTime = 2000235,//通知桌子续费信息
    Msg_SynDeskLessFive = 2000276,//通知桌子剩余时长

    /// <summary>
    ///排队等坐5001018
    /// </summary>
    Msg_LineUpRq = 5001018,
    Msg_LineUpRs = 2000238,

    /// <summary>
    /// 排队等坐列表 5001019
    /// </summary>
    Msg_LineUpListRq = 5001019,
    Msg_LineUpListRs = 2000239,

    /// <summary>
    /// 推送玩家获得 jackpot 奖励信息 2000241
    /// </summary>
    Msg_SynJackpotAwardGiving = 2000241,

    /// <summary>
    /// 创建牌桌消耗配置 4000116
    /// </summary>
    Msg_CreateDeskConfigRq = 4000116,
    Msg_CreateDeskConfigRs = 2100018,

    /// <summary>
    /// 回放操作 4000230
    /// </summary>
    Msg_PlayBackRq = 4000230,
    Msg_PlayBackRs = 2000268,
    Msg_PlayBackRs_zjh = 2000409,

    /// <summary>
    /// 收藏当局游戏 4000241
    /// </summary>
    Msg_CollectRoundRq = 4000241,
    Msg_CollectRoundRs = 2000269,

    /// <summary>
    /// 我的牌谱 4000229
    /// </summary>
    Msg_MyPaiPuRq = 4000229,
    Msg_MyPaiPuRs = 2000267,

    /// <summary>
    /// 创建房间默认配置 4000238
    /// </summary>
    Msg_DefaultCreateDeskRq = 4000238,
    Msg_DefaultCreateDeskRs = 2100023,

    //找回密码4000239
    Msg_FindPwdRq = 1900010,
    Msg_FindPwdRs = 2000287,

    //找回安全码4000239
    Msg_FindSafePwdRq = 4000240,
    Msg_FindSafePwdRs = 2000288,

    //获取牌桌信息4000250
    Msg_GetDeskInfoRq = 4000250,
    //获取牌桌信息返回2000119
    Msg_GetDeskInfoRs = 2000119,

    #endregion

    #region  Msg_League.proto

    /// <summary>
    ///创建工会
    /// </summary>
    Msg_CreateLeagueRq = 4000201,
    Msg_CreateLeagueRs = 2000201,
    /// <summary>
    ///我的联盟或者俱乐部详细信息登录推送
    /// </summary>
    Msg_SynLeagueDetail = 2100016,

    /// <summary>
    ///注销俱乐部回包
    /// </summary>
    Msg_DisMissLeagueRq = 4000202,
    Msg_DisMissLeagueRs = 4000202,

    /// <summary>
    ///加入俱乐部4000203
    /// </summary>
    Msg_JoinLeagueRq = 4000203,
    Msg_JoinLeagueRs = 2000203,


    /// <summary>
    ///退出俱乐部 俱乐部会长退出即解散俱乐部
    /// </summary>
    Msg_QuitLeagueRq = 4000204,
    Msg_QuitLeagueRs = 2000204,

    /// <summary>
    ///修改俱乐部信息
    /// </summary>
    Msg_ModifyLeagueRq = 4000205,
    Msg_ModifyLeagueRs = 2000205,

    /// <summary>
    ///成员列表
    /// </summary>
    Msg_LeagueUserListRq = 4000206,
    Msg_LeagueUserListRs = 2000206,

    /// <summary>
    ///我的俱乐部列表
    /// </summary>
    Msg_MyLeagueListRq = 4000207,
    Msg_MyLeagueListRs = 2000207,

    /// <summary>
    ///申请加入俱乐部列表登录推送2100006
    /// </summary>
    Msg_SynApplyList = 2100006,
    Msg_SynApplyInfo = 2100007,

    /// <summary>
    ///玩家申请加入俱乐部处理
    /// </summary>
    Msg_ApplyLeagueRq = 4000208,
    Msg_ApplyLeagueRs = 2000208,

    //踢出玩家4000209
    Msg_RemovePlayerRq = 4000209,
    Msg_RemovePlayerRs = 2000240,

    //成员变动日志4000210
    Msg_ClubUserChangeRq = 4000210,
    Msg_ClubUserChangeRs = 2000242,

    //俱乐部变动日志4000211
    Msg_UnionClubChangeRq = 4000211,
    Msg_UnionClubChangeRs = 2000243,

    //获取jackpot配置信息4000212
    Msg_GetJackpotConfigRq = 4000212,
    Msg_SynJackpotConfigRs = 2000244,

    //修改jackpot 4000213
    Msg_SetJackpotConfigRq = 4000213,
    Msg_SetJackpotConfigRs = 2000245,

    //联盟局进牌桌后获取对应jackpot 4000214
    Msg_Get_JackpotRq = 4000214,
    Msg_Get_JackpotRs = 2100010,

    //俱乐部向联盟申请联盟币4000215
    Msg_ApplyClubGoldRq = 4000215,
    Msg_ApplyClubGoldRs = 2000246,
    //2000247 推送俱乐部联盟币申请信息
    Msg_SynApplyClubGold = 2000247,

    //处理申请信息4000216
    Msg_ApplyClubGoldOptionRq = 4000216,
    Msg_ApplyClubGoldOptionRs = 2000248,

    //获取俱乐部的申请记录4000217
    Msg_GetApplyClubGoldListRq = 4000217,
    Msg_GetApplyClubGoldListRs = 2000249,

    //牌局记录4000218
    Msg_ClubDeskLogRq = 4000218,
    Msg_ClubDeskLogRs = 2000250,


    //设置备注4000219
    Msg_SetRemarkRq = 4000219,
    Msg_SetRemarkRs = 2000251,

    //搜索俱乐部 联盟4000220
    Msg_SearchClubRq = 4000220,
    Msg_SearchClubRs = 2000252,


    //设置玩家资金4000221
    Msg_SetClubUserCapitalRq = 4000221,
    Msg_SetClubUserGoldRs = 2000253,

    //查看俱乐部资金明细4000222
    Msg_SearchClubCapitalRq = 4000222,
    Msg_SearchClubCapitalRs = 2000254,

    //俱乐部战绩4000223
    Msg_ClubRecordRq = 4000223,
    Msg_ClubRecordRs = 2000258,

    //俱乐部战绩一日总计4000224
    Msg_ClubDayTotalRq = 4000224,
    Msg_ClubDayTotalRs = 2000259,

    //俱乐部战绩 牌局列表4000225
    Msg_ClubRecordDeskRq = 4000225,
    Msg_ClubRecordDeskRs = 2000260,

    //jackpo奖池记录4000226
    Msg_JackPotReportRq = 4000226,
    Msg_JackPotReportRs = 2000261,

    //联盟组织财产4000227
    Msg_UnionRecordRq = 4000227,
    Msg_UnionRecordRs = 2001005,


    ///联盟相关----------------------------
    //设置俱乐部额度4001001
    Msg_SetClubGoldRq = 4001001,
    Msg_SetClubGoldRs = 2001001,

    //加入联盟4001002
    Msg_JoinUnionRq = 4001002,
    Msg_JoinUnionRs = 2000262,

    //加入超盟4001011
    Msg_JoinSuperUnionRq = 4001011,
    Msg_JoinSuperUnionRs = 2000281,

    //推送加入超盟的申请2100025
    Msg_SynJoinSuperUnionApplyRs = 2100025,

    //获取加入超盟的申请信息4001012
    Msg_GetJoinSuperUnionApplyRq = 4001012,
    Msg_GetJoinSuperUnionApplyRs = 2000282,

    //处理加入超盟4001013
    Msg_HandelJoinSuperUnionRq = 4001013,
    Msg_HandelJoinSuperUnionRs = 2000283,

    //超盟子联盟4001014
    Msg_GetSuperUnionListRq = 4001014,
    Msg_GetSuperUnionListRs = 2000284,

    //申请加入联盟列表实时推送2100013
    Msg_SynApplyUnion = 2100013,
    //申请加入联盟列表登录推送2100012
    Msg_SynApplyUnionList = 2100012,
    Msg_getApplyClubInfoRq = 4000237,

    //俱乐部申请加入联盟处理 4001003
    Msg_ApplyClubRq = 4001003,
    Msg_ApplyClubRs = 2001002,

    //退出联盟4001004
    Msg_QuitUnionRq = 4001004,
    Msg_QuitUnionRs = 2001003,

    //移除俱乐部4001005
    Msg_RemoveClubRq = 4001005,
    Msg_RemoveClubRs = 2001004,

    //联盟邀请俱乐部4001006
    Msg_InvitationClubRq = 4001006,
    Msg_InvitationClubRs = 2000255,

    //通知有邀请信息2000256
    Msg_SynInvitationInfo = 2000256,
    //登录推送自身收到的邀请信息2100019
    Msg_SynInvitationInfoList = 2100019,

    //俱乐部处理联盟邀请4001007
    Msg_OptionInvitationClubRq = 4001007,
    Msg_OptionInvitationClubRs = 2000257,

    //4001008俱乐部
    Msg_GetUnionClubListRq = 4001008,
    Msg_GetUnionClubListRs = 2000263,

    //玩家像俱乐部申请资金操作4001009
    Msg_UserApplyClubCapitalRq = 4001009,
    Msg_UserApplyClubCapitalRs = 2000265,

    //处理玩家申请信息4001010
    Msg_UserApplyClubOptionRq = 4001010,
    Msg_UserApplyClubOptionRs = 2000266,

    //盟主钻石换联盟币4000233
    Msg_DiamondChangeGoldRq = 4000233,
    Msg_DiamondChangeGoldRs = 2000272,


    #endregion

    #region  Msg_GameCommon.proto

    //房间封禁信息列表4000121
    Msg_BlackListRq = 4000121,
    Msg_BlackListRs = 2000289,

    #endregion

    #region  Msg_NiuNiuDesk.proto

    /// <summary>
    ///进入牛牛桌子
    /// </summary>
    Msg_EnterNiuNiuDeskRs = 2000210,
    /// <summary>
    ///通知游戏状态改变
    /// </summary>
    Syn_DeskUpdate = 2000301,
    /// <summary>
    ///发牌
    /// </summary>
    MsgDealCard = 2000302,


    /// <summary>
    ///抢庄
    /// </summary>
    Msg_RobBanker = 5001101,


    /// <summary>
    ///推送庄家
    /// </summary>
    Msg_SynBanker = 2000304,

    /// <summary>
    ///下注
    /// </summary>
    Msg_BetCoin = 5001102,

    /// <summary>
    ///翻牌
    /// </summary>
    Msg_ShowCard = 5001103,

    /// <summary>
    ///抢庄
    /// </summary>
    Syn_RobBanker = 2000303,
    /// <summary>
    ///下注
    /// </summary>
    Syn_BetCoin = 2000305,
    /// <summary>
    ///翻牌
    /// </summary>
    Syn_ShowCard = 2000306,

    /// <summary>
    ///结算
    /// </summary>
    Syn_Settle = 2000307,

    /// <summary>
    ///上局回顾
    /// </summary>
    /// 
    Msg_LastHistoryRq = 5001104,
    Msg_LastHistoryRs = 2000308,
    Msg_ZjhLastHistoryRs = 2000408,



    #endregion

    #region  Msg_ZjhDesk.proto

    /// <summary>
    ///进入炸金花桌子
    /// </summary>
    Msg_EnterZjhDeskRs = 2000401,
    /// <summary>
    ///更换操作对象2000402
    /// </summary>
    Syn_ChangeOperation = 2000402,
    /// <summary>
    ///操作信息2000403
    /// </summary>
    Syn_OptionInfo = 2000403,

    /// <summary>
    ///看牌2000404
    /// </summary>
    Syn_LookCard = 2000404,

    /// <summary>
    /// 操作请求5002201
    /// </summary>
    Msg_OptionRq = 5002201,

    /// <summary>
    ///推送比牌信息2000405
    /// </summary>
    Syn_CompareCard = 2000405,

    /// <summary>
    /// 牌桌底池变动2000406
    /// </summary>
    Syn_ZjhPotChange = 2000406,
    /// <summary>
    ///结算2000407
    /// </summary>
    Syn_ZjhSettle = 2000407,

    //提前结算
    Msg_AdvanceSettleRq = 5001009,
    Msg_AdvanceSettleRs = 2000221,

    //搓牌5001105
    Msg_LookRq = 5001105,

    //2000309搓牌返回
    Msg_LookRs = 2000309,

    //搓牌开关//5001106
    Msg_AutoLookRq = 5001106,

    //2000310搓牌开关
    Msg_AutoLookRs = 2000310,

    Syn_AutoShowCard = 2000311,

    #endregion

    #region  Msg_TexasDesk.proto
    Msg_EnterTexasDeskRs = 2000506, //进入德州桌子2000506
    Syn_TexasStart = 2000501, //游戏开始
    Msg_TexasOption = 5003001, //操作信息
    Syn_TexasOptionInfo = 2000502, //操作信息
    Syn_TexasChangeOption = 2000503, //更换操作对象
    Syn_DealCommonCard = 2000505, //发牌  公牌3 转牌1 河牌1

    Msg_SynTexasSettle = 2000504, //结算

    Msg_EdgePot = 2000507, //主池 边池信息
    Msg_TexasLastHistoryRs = 2000508, //上局回顾
    Msg_TexasPokerPlayBackRs = 2000509, //德州扑克回放

    Msg_SynTexasPokerHandCards = 2000510, //推送玩家手牌

    Msg_ProtectInfo = 2000511, //保险信息

    Msg_BuyProtectCardRq = 5003002, //购买保险

    Msg_BuyProtectCardRs = 2000512, //购买保险返回

    Msg_SynProtectCard = 2000513, //推送保险信息

    Msg_SynTexasState = 2000514, //推送牌桌状态变更(保险)
    Msg_LookCardRq = 5001023, //看手牌
    Msg_LookCardRs = 2000279, //看手牌返回
    Msg_LookCommonCardRq = 5001024, //看公牌
    Msg_LookCommonCardRs = 2000280, //看公牌返回

    Msg_TexasRandomPosRq = 5003003, //随机座位

    Msg_TexasRandomPosRs = 2000515, //随机座位返回
    Msg_ProtectInfo_end = 2000516, //保险结束
    Msg_BackPot = 2000517, //底池退回2000517

    Msg_DeskBlackListRq = 5001025, //获取黑名单
    Msg_DeskBlackListRs = 2000285, //获取黑名单返回
    Msg_RemoverDeskBlackRq = 5001026, //移出黑名单
    Msg_RemoverDeskBlackRs = 2000286, //黑名单推送

    #endregion

    #region  Msg_CompareChickenDeskProto.proto

    Msg_EnterCompareChickenDeskRs = 2000605, //进入比鸡鸡桌子2000605
    Msg_CompareCardRq = 5005001, //组牌5005001
    Msg_CompareCardRs = 2000601, //组牌回包2000601
    Msg_SynCompareCard = 2000602, //推送玩家组牌完成2000602
    Msg_AutoCompareCardRq = 5005002, //自动组牌5005002
    Msg_AutoCompareCardRs = 2000603, //自动组牌回包2000603
    Syn_CompareChickenSettle = 2000604, //结算2000604
    Msg_CompareCardGiveRq = 5005003, //弃牌5005003
    Msg_CompareCardGiveRs = 2000606, //弃牌回包2000606
    Msg_SynPlayerGiveCard = 2000607, //推送玩家投降2000607
    Syn_CompareChickenState = 2000608, //切换牌桌状态2000608
    Msg_CKLastHistoryRs = 2000609,//牌局回顾2000609
    Msg_CKPlayBackRs = 2000610,//比鸡牌局回放2000610
    Msg_SynCKJackPot = 2000611, //推送奖池得奖通知

    #endregion

    #region  Msg_MatchProto.proto

    /// <summary>
    /// 获取赛制信息 4000401
    /// </summary>
    Msg_getMatchRq = 4000401,

    /// <summary>
    /// 赛程返回 2000701
    /// </summary>
    Msg_getMatchRs = 2000701,

    /// <summary>
    /// 门票信息更新2000709
    /// </summary>
    Msg_MatchTicketsRs = 2000709,

    /// <summary>
    /// 门票信息更新2000710
    /// </summary>
    Syn_MatchTicketsUpdate = 2000710,

    /// <summary>
    /// 赛制信息通知 2000702
    /// </summary>
    Syn_Match = 2000702,

    /// <summary>
    /// 通知比赛还有1分钟开始 2000704
    /// </summary>
    Syn_Notice_Match_Start = 2000704,

    /// <summary>
    /// 报名比赛 4000402
    /// </summary>
    Msg_SignUpMatchRq = 4000402,

    /// <summary>
    /// 报名比赛返回 2000703
    /// </summary>
    Msg_SignUpMatchRs = 2000703,

    /// <summary>
    /// 确认参与比赛 4000404
    /// </summary>
    Msg_SureJoinMatchRq = 4000404,

    /// <summary>
    /// 确认参与返回 2000705
    /// </summary>
    Msg_SureJoinMatchRs = 2000705,

    /// <summary>
    /// 比赛牌桌信息 4000405
    /// </summary>
    Msg_MatchDeskListRq = 4000405,

    /// <summary>
    /// 比赛牌桌信息返回 2000706
    /// </summary>
    Msg_MatchDeskListRs = 2000706,

    /// <summary>
    /// 比赛排名信息 4000406
    /// </summary>
    Msg_MatchRankListRq = 4000406,

    /// <summary>
    /// 比赛排名信息返回 2000707
    /// </summary>
    Msg_MatchRankListRs = 2000707,

    /// <summary>
    /// 比赛奖励 4000407
    /// </summary>
    Msg_MatchRewardRq = 4000407,

    /// <summary>
    /// 比赛奖励返回 2000708
    /// </summary>
    Msg_MatchRewardRs = 2000708,

    /// <summary>
    /// 通知比赛结束 2000710
    /// </summary>
    Msg_SynMatchEnd = 2000710,

    /// <summary>
    /// 获取赛制信息 4000408
    /// </summary>
    Msg_getSingleMatchRq = 4000408,

    /// <summary>
    /// 赛程返回 2000711
    /// </summary>
    Msg_getSingleMatchRs = 2000711,

    //进入匹配 2000712
    Msg_SynMatching = 2000712,

    //通知被淘汰2000714
    Msg_SynMatchLose = 2000714,

    //通知比赛第一名2000715
    Msg_SynMatchFirst = 2000715,

    #endregion

    #region  俱乐部战队

    /// <summary>
    ///俱乐部战队
    /// </summary>
    Msg_ClubTeamRq = 4001015,
    Msg_ClubTeamRs = 2000290,

    /// <summary>
    ///战队成员
    /// </summary>
    Msg_ClubTeamUserRq = 4001016,
    Msg_ClubTeamUserRs = 2000291,

    /// <summary>
    ///设置战队队长
    /// </summary>
    Msg_SetClubTeamLeaderRq = 4001017,
    Msg_SetClubTeamLeaderRs = 2000292,

    /// <summary>
    ///设置战队成员
    /// </summary>
    Msg_SetClubTeamPlayerRq = 4001018,
    Msg_SetClubTeamPlayerRs = 2000293,

    /// <summary>
    ///设置成员分成
    /// </summary>
    Msg_SetClubTeamRebateRq = 4001019,
    Msg_SetClubTeamRebateRs = 2000294,

    /// <summary>
    ///抽水明细
    /// </summary>
    Msg_GetClubTeamRateRq = 4001020,
    Msg_GetClubTeamRateRs = 2000295,

    #endregion

    #region  麻将
    /// <summary>
    ///游戏开始
    /// </summary>
    PBMJStart = 2008002,
    /// <summary>
    ///进入麻将桌子
    /// </summary>
    Msg_EnterMJDeskRs = 2008001,
    //麻将操作5006001
    Msg_MJOptionRq = 5006001,
    //摸牌2008003
    Msg_MJOption1 = 2008003,
    //出牌2008004
    Msg_MJOption2 = 2008004,
    //吃2008005
    Msg_MJOption3 = 2008005,
    //碰2008006
    Msg_MJOption4 = 2008006,
    //杠2008007
    Msg_MJOption5 = 2008007,
    //听2008008
    Msg_MJOption6 = 2008008,
    //过2008010
    Msg_MJOption7 = 2008010,
    //2008016通知有操作
    Msg_MJOption8 = 2008016,
    //2008017积分变化
    Syn_HHCoinChange = 2008017,
    //麻将桌子状态变化2008019
    MSG_ChangeMJDeskState = 2008019,
    //通知玩家托管2000296
    Syn_PlayerAuto = 2000296,
    //取消托管5001032
    Msg_CancelAutoRq = 5001032,

    #region 卡五星
    //飘请求5006005
    Msg_PiaoRq = 5006005,
    //飘返回2008019
    Msg_SynPiaoRs = 2008018,
    //换牌请求
    Msg_ChangeCardRq = 5006006,
    //换牌返回2008020
    Msg_ChangeCardRs = 2008020,
    //广播玩家换牌完成2008022
    Msg_SynChangeCardRs = 2008022,
    //换牌结束 更新手牌2008021
    Msg_SynHandCard = 2008021,
    //亮倒请求5006007
    Msg_LiangDaoRq = 5006007,
    //2008023展示的牌
    Msg_SynPlayerHandCard = 2008023,
    #endregion

    #region 血流
    //甩牌请求5006008
    Msg_ThrowCardRq = 5006008,
    //甩牌返回2008024
    Msg_ThrowCardRs = 2008024,
    //2008025血流连续胡牌
    Msg_MJOption9 = 2008025,
    //血流结算2008026
    Msg_XlSettle = 2008026,
    #endregion

    //胡2008009
    Msg_Hu = 2008009,
    //流局2008011 [已废弃] 现在流局通过Msg_Hu中的liuJu字段判断
    //Msg_LoseGame = 2008011,
    //麻将准备5006002
    Msg_MJReadyRq = 5006002,
    //麻将准备返回2008012
    Msg_MJReadyRs = 2008012,
    //麻将准备同步2008013
    Msg_SynMJReady = 2008013,
    //申请解散房间5006003
    Msg_ApplyMJDismissRq = 5006003,
    //广播2008014申请解散
    Msg_SynMJDismiss = 2008014,
    //处理解散请求5006004
    Msg_ProcessDismissRq = 5006004,
    //通知是否同意解散2008015
    Msg_SynProcessDismiss = 2008015,

    /// <summary>
    ///创建楼层
    /// </summary>
    Msg_CreateMjFloorRq = 4000501,
    Msg_CreateMjFloorRs = 2009001,

    /// <summary>
    /// 删除楼层
    /// </summary>
    Msg_DelMjFloorRq = 4000502,
    Msg_DelMjFloorRs = 2009002,

    /// <summary>
    /// 设置楼层
    /// </summary>
    Msg_SetMjFloorRq = 4000503,
    Msg_SetMjFloorRs = 2009003,

    /// <summary>
    /// 获取所有楼层信息
    /// </summary>
    Msg_GetMjFloorRq = 4000504,
    Msg_GetMjFloorRs = 2009004,

    /// <summary>
    /// 获取楼层信息
    /// </summary>
    Msg_EnterMjFloorRq = 4000505,
    Msg_EnterMjFloorRs = 2009005,

    /// <summary>
    /// 混排设置
    /// </summary>
    Msg_SetHallRq = 4000506,
    Msg_SetHallRs = 2009006,

    /// <summary>
    /// 大厅设置
    /// </summary>
    Msg_SetHallFloorRq = 4000507,
    Msg_SetHallFloorRs = 2009007,

    /// <summary>
    ///楼层变动
    /// </summary>
    Msg_SynFloorChange = 2009008,

    /// <summary>
    /// 房间人数变化通知
    /// </summary>
    Msg_SynFloorDeskChange = 2009009,

    /// <summary>
    /// 我的战绩/俱乐部战绩
    /// </summary>
    Msg_MJMYRecordRq = 4000242,
    Msg_MJMYRecordRs = 2009010,

    /// <summary>
    /// 成员战绩
    /// </summary>
    Msg_MJTeamRecordRq = 4000243,
    Msg_MJTeamRecordRs = 2009011,

    /// <summary>
    /// 我的战绩详情
    /// </summary>
    Msg_MJMYRecordDetailRq = 4000244,
    Msg_MJMYRecordDetailRs = 2009012,

    /// <summary>
    /// 麻将回放
    /// </summary>
    Msg_MJPlayBackRq = 4000245,
    Msg_MJPlayBack = 2000612,

    #endregion

    #region 跑的快
    Syn_ChangeRunFastDeskState = 2010001,//桌子状态变更
    Syn_RunFastDealCard = 2010002,//发牌
    Msg_EnterRunFastDeskRs = 2010004,// 进入牌桌
    Msg_RanFastDiscardRq = 5007002,//出牌请求
    Syn_RunFastDiscardCard = 2010005,//出牌同步
    Syn_RunFastSettle = 2010006,//结算
    Msg_RunFastPlayBackRq = 4000246,//跑的快回放请求
    Msg_RunFastPlayBackRs = 2000613,//跑的快回放
    Msg_RanFastRobBankerRq = 5007003,//抢庄请求
    Msg_RanFastRobBankerRs = 2010007,//抢庄返回
    Msg_RanFastDoubleRq = 5007001,//加倍请求
    Syn_RanFastDouble = 2010003,//加倍同步
    #endregion

    #region 祈福
    //祈福配置请求4000251
    Msg_PrayConfigRq = 4000251,
    Msg_PrayConfigRs = 2000120,
    //祈福请求4000252
    Msg_PrayRq = 5000012,
    Msg_PrayRs = 2000121,
    //祈福同步2000122
    SynPrayRs = 2000122,
    //祈福奖励4000252
    Msg_PrayRewardRq = 4000252,
    //祈福奖励2000123
    Msg_PrayRewardRs = 2000123,
    #endregion

}




